In [1]:
# Librerias necesarias
from CoffeaDelphes import Converter
import numpy as np
import matplotlib.pyplot as plt
from hist import Hist
import mplhep as hep
import pandas as pd
import glob
import coffea

plt.style.use([hep.style.ROOT])

import warnings
warnings.filterwarnings('ignore')

In [7]:
def eff_corte(before,after): return len(after)/len(before)

# ***** Signal Efficiency Analysis --> S

In [17]:
data_final_signal = pd.read_csv("data_final_signal.csv")
data_final_signal.head()

,jet_pt_b1,jet_pt_b2,jet_eta_b1,jet_eta_b2,jet_phi_b1,jet_phi_b2,jet_mass_b1,jet_mass_b2,Delta_eta_b,Delta_phi_b,...,j2_j3,b0_b1,b0_j0,b0_j1,b1_j0,b1_j1,metphi_j0,metphi_j1,metphi_j2,metphi_j3
0,36.520973,30.758999,0.409347,1.242087,1.015780,2.322117,3.420154,4.004740,0.832740,1.306336,...,1.365764,1.306336,NaN,1.306336,1.306336,4.440892e-16,0.548285,0.758051,2.727849,2.189572
1,30.415281,14.244907,-0.723814,-1.353978,-2.900409,-0.205079,6.192515,3.142711,-0.630164,2.695330,...,2.036914,2.695330,NaN,2.695330,2.695330,5.551115e-17,2.625057,0.962797,0.257138,2.294052
2,38.492733,17.479437,1.769234,2.213748,3.118397,-1.915401,5.367582,3.574377,0.444513,1.249388,...,1.747631,1.249388,NaN,2.557579,1.249388,2.476219e+00,0.920562,2.805044,0.328825,2.076457
3,19.937721,15.938089,-0.101928,0.890768,-3.104975,1.443351,3.958317,1.914171,0.992696,1.734860,...,1.979895,1.734860,2.221924,NaN,2.326402,1.734860e+00,1.833791,2.227471,1.487285,0.492611
4,29.754230,11.970448,-0.044334,-1.366111,-2.396115,0.740930,5.236414,2.407120,-1.321776,3.137044,...,0.570770,3.137044,NaN,1.894892,3.137044,1.242153e+00,1.901714,2.486579,1.244427,0.673657

#### Corte 1: $| \Delta \phi(j0,j1)| > 1 $

In [18]:
data_signal_cut1 = data_final_signal[(data_final_signal.j0_j1 > 1)]
data_signal_cut1.head()

,jet_pt_b1,jet_pt_b2,jet_eta_b1,jet_eta_b2,jet_phi_b1,jet_phi_b2,jet_mass_b1,jet_mass_b2,Delta_eta_b,Delta_phi_b,...,j2_j3,b0_b1,b0_j0,b0_j1,b1_j0,b1_j1,metphi_j0,metphi_j1,metphi_j2,metphi_j3
0,36.520973,30.758999,0.409347,1.242087,1.015780,2.322117,3.420154,4.004740,0.832740,1.306336,...,1.365764,1.306336,NaN,1.306336,1.306336,4.440892e-16,0.548285,0.758051,2.727849,2.189572
1,30.415281,14.244907,-0.723814,-1.353978,-2.900409,-0.205079,6.192515,3.142711,-0.630164,2.695330,...,2.036914,2.695330,NaN,2.695330,2.695330,5.551115e-17,2.625057,0.962797,0.257138,2.294052
2,38.492733,17.479437,1.769234,2.213748,3.118397,-1.915401,5.367582,3.574377,0.444513,1.249388,...,1.747631,1.249388,NaN,2.557579,1.249388,2.476219e+00,0.920562,2.805044,0.328825,2.076457
3,19.937721,15.938089,-0.101928,0.890768,-3.104975,1.443351,3.958317,1.914171,0.992696,1.734860,...,1.979895,1.734860,2.221924,NaN,2.326402,1.734860e+00,1.833791,2.227471,1.487285,0.492611
4,29.754230,11.970448,-0.044334,-1.366111,-2.396115,0.740930,5.236414,2.407120,-1.321776,3.137044,...,0.570770,3.137044,NaN,1.894892,3.137044,1.242153e+00,1.901714,2.486579,1.244427,0.673657

In [19]:
print("La eficiencia de corte es:", eff_corte(data_final_signal,data_signal_cut1))

La eficiencia de corte es: 0.935192648718362

#### Corte 2: $| \Delta \phi(b0,b1)| > 1 $

In [20]:
data_signal_cut2 = data_final_signal[(data_final_signal.b0_b1 > 1)]
data_signal_cut2.head()

,jet_pt_b1,jet_pt_b2,jet_eta_b1,jet_eta_b2,jet_phi_b1,jet_phi_b2,jet_mass_b1,jet_mass_b2,Delta_eta_b,Delta_phi_b,...,j2_j3,b0_b1,b0_j0,b0_j1,b1_j0,b1_j1,metphi_j0,metphi_j1,metphi_j2,metphi_j3
0,36.520973,30.758999,0.409347,1.242087,1.015780,2.322117,3.420154,4.004740,0.832740,1.306336,...,1.365764,1.306336,NaN,1.306336,1.306336,4.440892e-16,0.548285,0.758051,2.727849,2.189572
1,30.415281,14.244907,-0.723814,-1.353978,-2.900409,-0.205079,6.192515,3.142711,-0.630164,2.695330,...,2.036914,2.695330,NaN,2.695330,2.695330,5.551115e-17,2.625057,0.962797,0.257138,2.294052
2,38.492733,17.479437,1.769234,2.213748,3.118397,-1.915401,5.367582,3.574377,0.444513,1.249388,...,1.747631,1.249388,NaN,2.557579,1.249388,2.476219e+00,0.920562,2.805044,0.328825,2.076457
3,19.937721,15.938089,-0.101928,0.890768,-3.104975,1.443351,3.958317,1.914171,0.992696,1.734860,...,1.979895,1.734860,2.221924,NaN,2.326402,1.734860e+00,1.833791,2.227471,1.487285,0.492611
4,29.754230,11.970448,-0.044334,-1.366111,-2.396115,0.740930,5.236414,2.407120,-1.321776,3.137044,...,0.570770,3.137044,NaN,1.894892,3.137044,1.242153e+00,1.901714,2.486579,1.244427,0.673657

In [21]:
print("La eficiencia de corte es:", eff_corte(data_final_signal,data_signal_cut2))

La eficiencia de corte es: 0.857165887473803

# ***** Background Efficiency Analysis --> B1

In [12]:
data_final_bbbar = pd.read_csv("data_final_bbbar.csv")
data_final_bbbar.head()

,jet_pt_b1,jet_pt_b2,jet_eta_b1,jet_eta_b2,jet_phi_b1,jet_phi_b2,jet_mass_b1,jet_mass_b2,Delta_eta_b,Delta_phi_b,...,j2_j3,b0_b1,b0_j0,b0_j1,b1_j0,b1_j1,metphi_j0,metphi_j1,metphi_j2,metphi_j3
0,22.238794,20.841276,0.530937,1.747003,-0.445206,0.262520,4.680990,3.537635,1.216066,0.707727,...,1.645963,0.707727,2.827259,NaN,2.748200,0.707727,0.742731,2.084527,2.792254,1.844968
1,28.850031,7.613652,1.364405,1.589443,-2.467250,-2.990445,5.790969,1.479867,0.225038,0.523195,...,1.894580,0.523195,NaN,2.945903,0.523195,2.814087,2.899192,0.438090,2.012608,2.375997
2,75.119392,23.361349,0.800018,0.202338,0.652844,0.696416,5.695681,4.556839,-0.597680,0.043572,...,2.823785,0.043572,NaN,3.059460,0.043572,3.103031,2.707963,0.515763,2.664391,0.795009
3,29.302998,15.770082,-0.212805,-0.095042,-0.441010,-0.924416,4.767639,1.904579,0.117763,0.483406,...,0.822538,0.483406,2.584861,NaN,3.068267,0.483406,0.392811,2.192050,2.675456,2.785191
4,22.118122,14.628027,-1.933400,-2.037964,2.224194,2.678802,2.792423,0.000000,-0.104564,0.454609,...,0.316230,0.454609,2.887600,NaN,2.940977,0.454609,0.099055,2.986655,2.841921,3.125035

#### Corte 1: $| \Delta \phi(j0,j1)| > 1 $

In [13]:
data_bbbar_cut1 = data_final_bbbar[(data_final_bbbar.j0_j1 > 1)]
data_bbbar_cut1.head()

,jet_pt_b1,jet_pt_b2,jet_eta_b1,jet_eta_b2,jet_phi_b1,jet_phi_b2,jet_mass_b1,jet_mass_b2,Delta_eta_b,Delta_phi_b,...,j2_j3,b0_b1,b0_j0,b0_j1,b1_j0,b1_j1,metphi_j0,metphi_j1,metphi_j2,metphi_j3
0,22.238794,20.841276,0.530937,1.747003,-0.445206,0.262520,4.680990,3.537635,1.216066,0.707727,...,1.645963,0.707727,2.827259,NaN,2.748200,0.707727,0.742731,2.084527,2.792254,1.844968
1,28.850031,7.613652,1.364405,1.589443,-2.467250,-2.990445,5.790969,1.479867,0.225038,0.523195,...,1.894580,0.523195,NaN,2.945903,0.523195,2.814087,2.899192,0.438090,2.012608,2.375997
2,75.119392,23.361349,0.800018,0.202338,0.652844,0.696416,5.695681,4.556839,-0.597680,0.043572,...,2.823785,0.043572,NaN,3.059460,0.043572,3.103031,2.707963,0.515763,2.664391,0.795009
3,29.302998,15.770082,-0.212805,-0.095042,-0.441010,-0.924416,4.767639,1.904579,0.117763,0.483406,...,0.822538,0.483406,2.584861,NaN,3.068267,0.483406,0.392811,2.192050,2.675456,2.785191
4,22.118122,14.628027,-1.933400,-2.037964,2.224194,2.678802,2.792423,0.000000,-0.104564,0.454609,...,0.316230,0.454609,2.887600,NaN,2.940977,0.454609,0.099055,2.986655,2.841921,3.125035

In [14]:
print("La eficiencia de corte es:", eff_corte(data_final_bbbar,data_bbbar_cut1))

La eficiencia de corte es: 0.9265406114139811

#### Corte 2: $| \Delta \phi(b0,b1)| > 1 $

In [15]:
data_bbbar_cut2 = data_final_bbbar[(data_final_bbbar.b0_b1 > 1)]
data_bbbar_cut2.head()

,jet_pt_b1,jet_pt_b2,jet_eta_b1,jet_eta_b2,jet_phi_b1,jet_phi_b2,jet_mass_b1,jet_mass_b2,Delta_eta_b,Delta_phi_b,...,j2_j3,b0_b1,b0_j0,b0_j1,b1_j0,b1_j1,metphi_j0,metphi_j1,metphi_j2,metphi_j3
5,26.829123,9.700256,1.124120,0.158574,1.628139,-1.886546,3.264445,0.411303,-0.965546,2.768501,...,0.846167,2.768501,3.133570e+00,NaN,0.381115,2.768501,2.290959,0.842611,2.672074,2.764944
6,23.873981,20.378473,-1.152566,-2.042781,2.142433,-2.568795,3.820323,4.025971,-0.890215,1.571957,...,1.571957,1.571957,2.676810e-01,2.863371,1.839638,1.291414,2.929949,0.201103,2.662268,1.090311
9,30.389675,12.804542,1.983392,1.088431,2.545238,-0.834760,3.411311,2.252333,-0.894960,2.903187,...,2.921826,2.903187,3.095122e+00,NaN,0.191935,2.903187,0.716152,2.471911,0.908087,2.013739
16,32.072716,10.962624,-1.064338,-2.151680,1.947354,-1.122986,6.597967,1.047358,-1.087342,3.070340,...,1.570477,3.070340,2.220446e-16,2.691493,3.070340,0.521352,1.565480,2.026212,1.504860,3.075337
17,25.326202,16.011299,0.167848,0.606571,-1.371698,2.027144,3.808955,2.499222,0.438723,2.884344,...,1.590298,2.884344,2.220446e-16,2.884344,2.884344,NaN,3.102819,0.218475,0.894428,2.484726

In [16]:
print("La eficiencia de corte es:", eff_corte(data_final_bbbar,data_bbbar_cut2))

La eficiencia de corte es: 0.5310882616796633

# ***** Background Efficiency Analysis --> B2

In [2]:
data_final_QCD = pd.read_csv("data_final_QCD.csv")
data_final_QCD.head()

,jet_pt_b1,jet_pt_b2,jet_eta_b1,jet_eta_b2,jet_phi_b1,jet_phi_b2,jet_mass_b1,jet_mass_b2,Delta_eta_b,Delta_phi_b,...,j2_j3,b0_b1,b0_j0,b0_j1,b1_j0,b1_j1,metphi_j0,metphi_j1,metphi_j2,metphi_j3
0,26.365898,14.738330,0.909281,0.433367,-0.506147,2.455689,3.832455,2.030266,-0.475914,2.961836,...,0.688693,2.961836,2.899246e-08,2.961836,2.961836,3.023682e-08,2.211716,0.750121,0.578122,1.266815
1,28.194830,21.970749,-1.366100,-0.894490,-1.105462,2.547144,3.135457,2.545112,0.471610,2.630579,...,2.268153,2.630579,6.510925e-09,2.630579,2.630579,1.299438e-08,2.963139,0.332560,1.776820,0.491333
2,24.602297,11.557791,0.190614,-0.393710,2.042665,2.039884,3.807051,1.378513,-0.584324,0.002781,...,2.976795,0.002781,4.314880e-08,3.052784,0.002781,3.050003e+00,3.061127,0.008343,3.058346,0.248044
3,25.880224,10.395804,1.021188,1.490858,-1.552950,2.156934,4.786191,1.863504,0.469670,2.573301,...,2.006255,2.573301,1.776733e-08,2.309189,2.573301,1.400696e+00,0.518695,2.827884,2.054606,2.222325
4,16.422308,14.717021,0.883234,1.719101,-0.726835,2.864033,3.217309,2.462832,0.835868,2.692317,...,1.673290,2.692317,8.750153e-09,2.692317,2.692317,1.622009e-08,0.417132,3.109449,0.716651,2.389940

#### Corte 1: $| \Delta \phi(j0,j1)| > 1 $

In [4]:
data_QCD_cut1 = data_final_QCD[(data_final_QCD.j0_j1 > 1)]
data_QCD_cut1.head()

,jet_pt_b1,jet_pt_b2,jet_eta_b1,jet_eta_b2,jet_phi_b1,jet_phi_b2,jet_mass_b1,jet_mass_b2,Delta_eta_b,Delta_phi_b,...,j2_j3,b0_b1,b0_j0,b0_j1,b1_j0,b1_j1,metphi_j0,metphi_j1,metphi_j2,metphi_j3
0,26.365898,14.738330,0.909281,0.433367,-0.506147,2.455689,3.832455,2.030266,-0.475914,2.961836,...,0.688693,2.961836,2.899246e-08,2.961836,2.961836,3.023682e-08,2.211716,0.750121,0.578122,1.266815
1,28.194830,21.970749,-1.366100,-0.894490,-1.105462,2.547144,3.135457,2.545112,0.471610,2.630579,...,2.268153,2.630579,6.510925e-09,2.630579,2.630579,1.299438e-08,2.963139,0.332560,1.776820,0.491333
2,24.602297,11.557791,0.190614,-0.393710,2.042665,2.039884,3.807051,1.378513,-0.584324,0.002781,...,2.976795,0.002781,4.314880e-08,3.052784,0.002781,3.050003e+00,3.061127,0.008343,3.058346,0.248044
3,25.880224,10.395804,1.021188,1.490858,-1.552950,2.156934,4.786191,1.863504,0.469670,2.573301,...,2.006255,2.573301,1.776733e-08,2.309189,2.573301,1.400696e+00,0.518695,2.827884,2.054606,2.222325
4,16.422308,14.717021,0.883234,1.719101,-0.726835,2.864033,3.217309,2.462832,0.835868,2.692317,...,1.673290,2.692317,8.750153e-09,2.692317,2.692317,1.622009e-08,0.417132,3.109449,0.716651,2.389940

In [8]:
print("La eficiencia de corte es:", eff_corte(data_final_QCD,data_QCD_cut1))

La eficiencia de corte es: 0.9276640716557844

#### Corte 2: $| \Delta \phi(b0,b1)| > 1 $

In [9]:
data_QCD_cut2 = data_final_QCD[(data_final_QCD.b0_b1 > 1)]
data_QCD_cut2.head()

,jet_pt_b1,jet_pt_b2,jet_eta_b1,jet_eta_b2,jet_phi_b1,jet_phi_b2,jet_mass_b1,jet_mass_b2,Delta_eta_b,Delta_phi_b,...,j2_j3,b0_b1,b0_j0,b0_j1,b1_j0,b1_j1,metphi_j0,metphi_j1,metphi_j2,metphi_j3
0,26.365898,14.738330,0.909281,0.433367,-0.506147,2.455689,3.832455,2.030266,-0.475914,2.961836,...,0.688693,2.961836,2.899246e-08,2.961836,2.961836,3.023682e-08,2.211716,0.750121,0.578122,1.266815
1,28.194830,21.970749,-1.366100,-0.894490,-1.105462,2.547144,3.135457,2.545112,0.471610,2.630579,...,2.268153,2.630579,6.510925e-09,2.630579,2.630579,1.299438e-08,2.963139,0.332560,1.776820,0.491333
3,25.880224,10.395804,1.021188,1.490858,-1.552950,2.156934,4.786191,1.863504,0.469670,2.573301,...,2.006255,2.573301,1.776733e-08,2.309189,2.573301,1.400696e+00,0.518695,2.827884,2.054606,2.222325
4,16.422308,14.717021,0.883234,1.719101,-0.726835,2.864033,3.217309,2.462832,0.835868,2.692317,...,1.673290,2.692317,8.750153e-09,2.692317,2.692317,1.622009e-08,0.417132,3.109449,0.716651,2.389940
8,36.929035,15.010123,-0.173553,0.493812,2.825594,0.163499,2.960818,2.852296,0.667365,2.662094,...,2.294284,2.662094,2.847290e-08,1.906272,2.662094,1.714819e+00,2.086790,2.290123,2.869588,0.575304

In [10]:
print("La eficiencia de corte es:", eff_corte(data_final_QCD,data_QCD_cut2))

La eficiencia de corte es: 0.7588000167420057

# Z Analysis

In [22]:
def Z(S,B): return S/np.sqrt(S+B)
def w(L,cs,N_mc): return (L*cs)/N_mc

#### Signal S

In [177]:
cs_s = 0.2 * 1000 # fb (cross section generacion MG) ** 1 pb -> 1000 fb 
N_mc_s = 50000 # numero eventos inicial
N_s1 = len(data_signal_cut1) # numero de eventos final corte 1
N_s2 = len(data_signal_cut2) # numero de eventos final corte 2
L = 3000 # fb^-1

In [178]:
S_1 = N_s1 * w(L,cs_s,N_mc_s)
S_2 = N_s2 * w(L,cs_s,N_mc_s)
print(S_1, " -- ", S_2)

69612.0  --  63804.0

#### Signal B1

In [179]:
cs_bbbar = 6.173970e+03 * 1000 # fb (cross section generacion MG) ** 1 pb -> 1000 fb 
N_mc_bbbar = 848568 # numero eventos inicial
N_bbbar1 = len(data_bbbar_cut1) # numero de eventos final corte 1
N_bbbar2 = len(data_bbbar_cut2) # numero de eventos final corte 2
L = 3000 # fb^-1

In [180]:
B1_1 = N_bbbar1 * w(L,cs_bbbar,N_mc_bbbar)
B1_2 = N_bbbar2 * w(L,cs_bbbar,N_mc_bbbar)
print(B1_1, " -- ", B1_2)

586127274.6910088  --  335965106.7681081

#### Signal B2

In [181]:
cs_qcd = 2.836e+06 * 1000 # fb (cross section generacion MG) ** 1 pb -> 1000 fb 
N_mc_qcd = 1000000 # numero eventos inicial
N_qcd1 = len(data_QCD_cut1) # numero de eventos final corte 1
N_qcd2 = len(data_QCD_cut1) # numero de eventos final corte 2
L = 3000 # fb^-1

In [182]:
B2_1 = N_qcd1 * w(L,cs_qcd,N_mc_qcd)
B2_2 = N_qcd2 * w(L,cs_qcd,N_mc_qcd)
print(B2_1, " -- ", B2_2)

754276740000.0  --  754276740000.0

#### B1 + B2

In [183]:
B_1 = B1_1 + B1_2
B_2 = B2_1 + B2_2

# Z

In [184]:
print("Z_A =",Z(S_1,B_1))
print("Z_B =",Z(S_2,B_2))

Z_A = 2.2923477558073198
Z_B = 0.05194784567324447